---
- name: Our First Playbook
  hosts: raiders
  gather_facts: yes # this is a default but we set as reminder
                        # this is alo called setup module or setup.py
                  
  tasks:
          - name: Install an application with apt
            apt:
                    state: "{{ lenny }}"
                    name: [sl,bastet,ninvaders]
                    # another way to write the list is shown below
                    #       - sl
                    #       - bastet
                    #       - ninvaders
            become: yes
        
