---
- name: Our 2nd playbook multi host
  hosts: planet-express

  tasks:
          - name: Manage apps with apt
            apt: 
                     name: sl
                     state: present
            become: yes
            when: ansible_os_family == "Debian"

          - name: Manage apps wth yum
            yum: 
                     name: sl
                     state: present
            become: yes               
            when: ansible_os_family == "RedHat"

