---
- name: Bootstrapping and newuser
  hosts: all
  gather_facts: yes


  vars: 
        uid: 1999
        usertocreate: pumpkinking
        grouptocreate: halloween

  vars_files: 
  #     - ~/pb03.yml      Home dir is secure
        - vars/pb03.yml

  tasks: 
  #      - name: "Ensure Python is installed on target hosts"
  #        raw:  "apt install -y python3-pip"
  #        become: yes

        - name: create a new group
          group: 
                name: "{{ grouptocreate }}"
                state: present
          become: yes

        - name: "Add {{ usertocreate }} with {{ uid }} and group {{ grouptocree }}"
          user: 
                name: "{{ usertocreate }}"
                comment:  "trying to create new user"      
                state: present
                shell: /bin/bash
                system: no
                createhome: yes
                group: "{{ grouptocreate }}"
                uid: "{{ uid }}"
          become: yes      
